# Week 4: Transfer Learning, BERT (Seminar)

### Using pretrained transformers (for fun, profit and 1 point)

There are many toolkits that let you access pretrained transformer models (like we used pretrained embeddings earlier), but the most powerful and convenient by far is 🤗[`huggingface/transformers`](https://github.com/huggingface/transformers). In this week's practice, you'll learn how to download, apply and modify pretrained transformers for a range of tasks. Buckle up, we're going in!


__Pipelines:__ if all you want is to apply a pretrained model, you can do that in one line of code using pipeline. Huggingface/transformers has a selection of pre-configured pipelines for masked language modelling, sentiment classification, question aswering, etc. ([see full list here](https://huggingface.co/transformers/main_classes/pipelines.html))

A typical pipeline includes:
* pre-processing, e.g. tokenization, subword segmentation
* a backbone model, e.g. bert finetuned for classification
* output post-processing

Let's see it in action:

In [ ]:
!pip install -U transformers datasets evaluate accelerate timm

In [1]:
from huggingface_hub import notebook_login

notebook_login()

C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import transformers
from transformers import pipeline

In [3]:
from accelerate import Accelerator

device = Accelerator().device

sentiment_clf = pipeline(
    "sentiment-analysis",
    "distilbert-base-uncased-finetuned-sst-2-english",
    device=device
)

sentiment_clf(["transformers library can be really useful!", "YSDA midterm is soon"])

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 4178.83it/s]

[{'label': 'POSITIVE', 'score': 0.9959487915039062},
 {'label': 'NEGATIVE', 'score': 0.986364483833313}]

In [ ]:
transformers.pipelines.SUPPORTED_TASKS.keys()

But how can we find out which model is suitable for chosen task in such a big models space?

Option 1: Using search and filters in [web](https://huggingface.co/models) (user-friendly)

Option 2: Using `huggingface_hub` library to access API from Python (if you want to automate some process)

In [4]:
import huggingface_hub

In [7]:
some_model = next(huggingface_hub.list_models())

some_model

ModelInfo(id='meta-models/Muse-Glimmer-30B', author=None, base_models=None, card_data=None, children_model_count=None, config=None, created_at=datetime.datetime(2026, 8, 9, 17, 51, 35, tzinfo=datetime.timezone.utc), disabled=None, downloads=121042, downloads_all_time=None, eval_results=None, gated=None, gguf=None, inference=None, inference_provider_mapping=None, last_modified=None, library_name='transformers', likes=1456, mask_token=None, model_index=None, pipeline_tag='image-text-to-text', private=False, resource_group=None, safetensors=None, security_repo_status=None, sha=None, siblings=None, spaces=None, tags=['transformers', 'safetensors', 'muse_glimmer', 'image-text-to-text', 'conversational', 'arxiv:2504.13181', 'arxiv:2602.06036', 'license:apache-2.0', 'eval-results', 'endpoints_compatible', 'region:us'], transformers_info=None, trending_score=1368, used_storage=None, widget_data=None)

In [8]:
filter = (
    "sentiment-analysis",
    "pytorch",
    "ru",
)

filtered_models = huggingface_hub.list_models(
    filter=filter,
    sort="downloads",
    limit=10,
)

print(f"Filtered by {filter}:")
for model in filtered_models:
    print(f"- https://huggingface.co/{model.id} ({model.downloads} downloads, {model.likes} likes)")

Filtered by ('sentiment-analysis', 'pytorch', 'ru'):
- https://huggingface.co/seara/rubert-base-cased-russian-sentiment (80456 downloads, 12 likes)
- https://huggingface.co/yangheng/deberta-v3-base-absa-v1.1 (48930 downloads, 74 likes)
- https://huggingface.co/seara/rubert-tiny2-russian-sentiment (19456 downloads, 35 likes)
- https://huggingface.co/r1char9/rubert-base-cased-russian-sentiment (11785 downloads, 13 likes)
- https://huggingface.co/seara/rubert-base-cased-russian-emotion-detection-ru-go-emotions (934 downloads, 4 likes)
- https://huggingface.co/seara/rubert-tiny2-russian-emotion-detection-ru-go-emotions (438 downloads, 13 likes)
- https://huggingface.co/yangheng/deberta-v3-large-absa-v1.1 (399 downloads, 26 likes)
- https://huggingface.co/seara/rubert-base-cased-russian-emotion-detection-cedr (238 downloads, 5 likes)
- https://huggingface.co/apkonsta/finrubert (198 downloads, 2 likes)
- https://huggingface.co/seara/rubert-tiny2-russian-emotion-detection-cedr (70 downloads, 1 likes)

Imagine the situation when you have a long text to read and a lack of time. Luckily, you've got an option to use one of pipelines! But which one?...

**Task 1 (0.5 points)**
- Find a suitable pipeline and model for text below
- Apply model to long text to get a short one
- Pretty-print the result and give an opinion if short text is good or not

In [5]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "facebook/bart-large-cnn"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.
Loading weights: 100%|██████████| 511/511 [00:00<00:00, 3057.22it/s]

In [21]:
long_text = """
The widespread adoption of remote work, accelerated by global events in the early 2020s, has triggered a significant and likely permanent shift in how we think about the workplace. This transition away from the traditional central office is having profound and multifaceted effects on urban economies, reshaping everything from commercial real estate to local small businesses.

One of the most immediate and visible impacts has been on the commercial real estate sector. With companies downsizing their physical footprints or adopting fully remote models, demand for office space has plummeted. This has led to rising vacancy rates, downward pressure on commercial rent prices, and a re-evaluation of the financial viability of large office buildings. City governments, which often rely heavily on property taxes from these high-value commercial properties, are now facing substantial budget shortfalls.

Furthermore, the daily rhythm of city centers has changed dramatically. The decline in the number of commuters has had a ripple effect on local businesses that once thrived on their patronage. Lunchtime cafes, after-work bars, dry cleaners, and public transit systems have all experienced a significant drop in revenue. This "doughnut effect" describes a phenomenon where the economic activity hollows out in the city center and increases in suburban residential areas as people work from home and spend their money locally.

However, it's not all negative. This shift also presents new opportunities. Some urban planners see a chance to repurpose vacant office buildings into much-needed residential housing, which could help address housing shortages and revitalize neighborhoods by creating 24/7 communities. Additionally, the ability to work remotely has spurred a reversal of rural depopulation in some regions, as professionals seek a better quality of life outside of major metropolitan areas, potentially distributing economic growth more evenly.

In conclusion, the remote work revolution is fundamentally restructuring urban economies. While it presents serious challenges to established systems like commercial real estate and downtown commerce, it also opens the door to innovative urban renewal and a more geographically dispersed economic landscape. The long-term effects will depend on how effectively cities and businesses can adapt to this new, more flexible paradigm.
"""

In [28]:
inputs = tokenizer(long_text, return_tensors="pt", truncation=True)
summary_ids = model.generate(**inputs, max_length=150, min_length=30, do_sample=False)
short_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print(short_text)

The widespread adoption of remote work has triggered a significant and likely permanent shift in how we think about the workplace. This transition away from the traditional central office is having profound and multifaceted effects on urban economies. The decline in the number of commuters has had a ripple effect on local businesses.

In [29]:
assert len(long_text) / len(short_text) > 5, "Too long, didn't read"

One of possible semi-supervised tasks used while BERT training is Masked Language Modeling. So our model have some text prediction capabilities!

In [ ]:
mlm_model = transformers.pipeline(
    task="fill-mask",
    model="bert-base-cased"
)

mlm_model("My name is [MASK] Shady!")

In order to make result more readable we can just take top-1 result:

In [31]:
mlm_model("My name is [MASK] Shady!")[0]["sequence"]

'My name is Slim Shady!'

**Task 2 (0.5 points)**
- Using BERT's ability to solve MLM task, find out answers on the following questions
- Perform some fact-checking, don't trust LLMs!

**Questions:**
- When YSDA was founded?
- Who invented radio first?
- What is the fifth Fibonacci number?

In [55]:
facts = [
    "Yandex School of Data Analysis was founded in [MASK].",
    "The inventor of radio was [MASK].",
    "The fifth Fibonacci number is [MASK]."
]

In [56]:
for fact in facts:
    print(mlm_model(fact)[0]["sequence"])

Yandex School of Data Analysis was founded in Japan.
The inventor of radio was unknown.
The fifth Fibonacci number is zero.

---

### The building blocks of a pipeline

Huggingface also allows you to access its pipelines on a lower level. There are two main abstractions for you:
* `Tokenizer` - converts from strings to token ids and back
* `Model` - a PyTorch `nn.Module` with pretrained weights

You can use such models as part of your regular PyTorch code: insert it as a layer in your model, apply to a batch of data, backpropagate, optimize, etc.

In [57]:
tokenizer = transformers.AutoTokenizer.from_pretrained("bert-base-uncased")
model = transformers.AutoModel.from_pretrained("bert-base-uncased")

C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\lymuthien\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
[transformers] loading configuration file config.json from cache at C:\Users\lymuthien\.cache\huggingface\hub\models--bert-base-uncased\snapshots\86b5e0934494bd15c9632b12f734a8a67f723594\config.json
[transformers] Model config BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

[transformers] loading configuration file config.json from cache at C:\Users\lymuthien\.cache\huggingface\hub\models--bert-base-uncased\snapshots\86b5e0934494bd15c9632b12f734a8a67f723594\config.json
[transformers] Model config BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

[transformers] loading weights file model.safetensors from cache at C:\Users\lymuthien\.cache\huggingface\hub\models--bert-base-uncased\snapshots\86b5e0934494bd15c9632b12f734a8a67f723594\model.safetensors
[transformers] Since the `dtype` attribute can't be found in model's config object, will use dtype=torch.float32 as derived from model's weights
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6590.03it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [58]:
lines = [
    "Luke, I am your father.",
    "Life is what happens when you're busy making other plans.",
    "I have no idea what pneumonoultramicroscopicsilicovolcanoconiosis is."
]

tokens_info = tokenizer(lines, padding=True, truncation=True, return_tensors="pt")
print("Tokenized:")
print(tokens_info)

print("\nDetokenized:")
for i in range(3):
    print(tokenizer.decode(tokens_info['input_ids'][i]))

Tokenized:
{'input_ids': tensor([[  101,  5355,  1010,  1045,  2572,  2115,  2269,  1012,   102,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [  101,  2166,  2003,  2054,  6433,  2043,  2017,  1005,  2128,  5697,
          2437,  2060,  3488,  1012,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [  101,  1045,  2031,  2053,  2801,  2054,  1052,  2638,  2819, 17175,
         11314,  6444,  2594,  7352, 26461, 27572, 11261,  6767, 15472,  6761,
          8663, 10735,  2483,  2003,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1]])}

Detokenized:
[CLS] luke, i am your father. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
[CLS] life is what happens when you ' re busy making other plans. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
[CLS] i have no idea what pneumonoultramicroscopicsilicovolcanoconiosis is. [SEP]

You can see some special tokens appeared besides our original text. They are usually used to give model some additional information, so model treats them in individual way.

You can list all special tokens used by tokenizer (moreover, you can add your own special tokens, but make sure you will show them to your model while training):

In [59]:
tokenizer._special_tokens_map

{'bos_token': None,
 'eos_token': None,
 'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]'}

In [60]:
tokenizer("First sentence", "Second sentence", return_token_type_ids=True)

{'input_ids': [101, 2034, 6251, 102, 2117, 6251, 102], 'token_type_ids': [0, 0, 0, 0, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

It's ineffective to put all possible tokens in vocabulary, but one also want to handle all possible text sequences instead of putting UNK everywhere.

WordPiece tokenization is here to help!

In [61]:
reversed_vocab = {token_id: token for token, token_id in tokenizer.vocab.items()}

In [62]:
for token_id in tokens_info["input_ids"][2]:
    print(reversed_vocab[token_id.item()], end=' ')

[CLS] i have no idea what p ##ne ##um ##ono ##ult ##ram ##ic ##ros ##copic ##sil ##ico ##vo ##lc ##ano ##con ##ios ##is is . [SEP]

Now you can apply tokenized data with model.

Depending on your task, you can use different part of output. For example, `[CLS]`-token output can be obtained by `pooler_output` key in model output.

In [6]:
import torch

In [64]:
with torch.no_grad():
    out = model(**tokens_info)

print(out['pooler_output'])

tensor([[-0.8854, -0.4722, -0.9392,  ..., -0.8081, -0.6955,  0.8748],
        [-0.9297, -0.5161, -0.9334,  ..., -0.9017, -0.7492,  0.9201],
        [-0.6808, -0.1979, -0.7096,  ..., -0.6691, -0.4557,  0.7595]])

Transformers knowledge hub: https://huggingface.co/transformers/



---

### Visualizing BERT

Interpretability of models is one of key factors of understanding their behaviour.

Neural Networks are harder to interpret than Classic ML models, but still it's not impossible!

Remember Attention mechanism? It's human-understandable concept: look closely to tokens which are more valuable for context of the current one.

In [65]:
!pip install bertviz

Collecting bertviz
  Downloading bertviz-1.4.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: transformers>=2.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from bertviz) (5.15.0)
Requirement already satisfied: torch>=1.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from bertviz) (2.7.1+cu128)
Requirement already satisfied: tqdm in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from bertviz) (4.67.1)
Collecting boto3 (from bertviz)
  Downloading boto3-1.43.71-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: requests in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from bertviz) (2.32.4)
Requirement already satisfied: regex in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from bertviz) (2026.2.28)
Collecting sentencepiece (from bertviz)
  Downloading sentencepiece-0.2.2-cp313-cp313-win_amd64.whl.metadata (34 kB)
Requirement already satisfied: IPython>=7.14 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from bertviz) (9.4.0)
Requirement already satisfied: colorama in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (0.4.6)
Requirement already satisfied: decorator in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (1.1.1)
Requirement already satisfied: jedi>=0.16 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (0.19.2)
Requirement already satisfied: matplotlib-inline in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (2.19.2)
Requirement already satisfied: stack_data in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from IPython>=7.14->bertviz) (5.14.3)
Requirement already satisfied: wcwidth in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->IPython>=7.14->bertviz) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jedi>=0.16->IPython>=7.14->bertviz) (0.8.4)
Requirement already satisfied: filelock in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.0->bertviz) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.0->bertviz) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.0->bertviz) (1.14.0)
Requirement already satisfied: networkx in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.0->bertviz) (3.5)
Requirement already satisfied: jinja2 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.0->bertviz) (3.1.6)
Requirement already satisfied: fsspec in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.0->bertviz) (2025.5.1)
Requirement already satisfied: setuptools in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.0->bertviz) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sympy>=1.13.3->torch>=1.0->bertviz) (1.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers>=2.0->bertviz) (1.27.0)
Requirement already satisfied: numpy>=1.17 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers>=2.0->bertviz) (2.1.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers>=2.0->bertviz) (25.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers>=2.0->bertviz) (6.0.2)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers>=2.0->bertviz) (0.22.2)
Requirement already satisfied: typer in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers>=2.0->bertviz) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers>=2.0->bertviz) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (0.28.1)
Requirement already satisfied: anyio in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (4.10.0)
Requirement already satisfied: certifi in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (2025.6.15)
Requirement already satisfied: httpcore==1.* in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (1.0.9)
Requirement already satisfied: idna in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (3.10)
Requirement already satisfied: h11>=0.16 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=2.0->bertviz) (1.3.1)
Collecting botocore<1.44.0,>=1.43.71 (from boto3->bertviz)
  Downloading botocore-1.43.71-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->bertviz)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3->bertviz)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from botocore<1.44.0,>=1.43.71->boto3->bertviz) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from botocore<1.44.0,>=1.43.71->boto3->bertviz) (2.4.0)
Requirement already satisfied: six>=1.5 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.71->boto3->bertviz) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->torch>=1.0->bertviz) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->bertviz) (3.4.2)
Requirement already satisfied: executing>=1.2.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data->IPython>=7.14->bertviz) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data->IPython>=7.14->bertviz) (3.0.0)
Requirement already satisfied: pure-eval in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from stack_data->IPython>=7.14->bertviz) (0.2.3)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers>=2.0->bertviz) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers>=2.0->bertviz) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=10.11.0->typer->transformers>=2.0->bertviz) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers>=2.0->bertviz) (0.1.2)
Downloading bertviz-1.4.1-py3-none-any.whl (157 kB)
Downloading boto3-1.43.71-py3-none-any.whl (140 kB)
Downloading botocore-1.43.71-py3-none-any.whl (15.6 MB)
   ---------------------------------------- 0.0/15.6 MB ? eta -:--:--
   -------- ------------------------------- 3.4/15.6 MB 21.4 MB/s eta 0:00:01
   ------------------- -------------------- 7.6/15.6 MB 19.6 MB/s eta 0:00:01
   ----------------------------------- ---- 13.9/15.6 MB 23.7 MB/s eta 0:00:01
   ---------------------------------------- 15.6/15.6 MB 23.2 MB/s  0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
Downloading sentencepiece-0.2.2-cp313-cp313-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 24.2 MB/s  0:00:00
Installing collected packages: sentencepiece, jmespath, botocore, s3transfer, boto3, bertviz

   ------ --------------------------------- 1/6 [jmespath]
   ------ --------------------------------- 1/6 [jmespath]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   ------------- -------------------------- 2/6 [botocore]
   -------------------- ------------------- 3/6 [s3transfer]
   -------------------- ------------------- 3/6 [s3transfer]
   -------------------- ------------------- 3/6 [s3transfer]
   -------------------------- ------------- 4/6 [boto3]
   -------------------------- ------------- 4/6 [boto3]
   -------------------------- ------------- 4/6 [boto3]
   -------------------------- ------------- 4/6 [boto3]
   --------------------------------- ------ 5/6 [bertviz]
   --------------------------------- ------ 5/6 [bertviz]
   --------------------------------- ------ 5/6 [bertviz]
   --------------------------------- ------ 5/6 [bertviz]
   ---------------------------------------- 6/6 [bertviz]

Successfully installed bertviz-1.4.1 boto3-1.43.71 botocore-1.43.71 jmespath-1.1.0 s3transfer-0.19.2 sentencepiece-0.2.2

In [7]:
from transformers import AutoTokenizer, AutoModel, utils
from bertviz import model_view, head_view

input_text = "Every time I try to interpret BERT model behaviour, I find new interesting patterns"
model = AutoModel.from_pretrained("bert-base-cased", output_attentions=True)
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4990.50it/s]
[transformers] BertModel LOAD REPORT from: bert-base-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [68]:
inputs = tokenizer.encode(input_text, return_tensors="pt")
outputs = model(inputs)
attention = outputs.attentions
tokens = tokenizer.convert_ids_to_tokens(inputs[0])

model_view(attention, tokens)

In [69]:
head_view(attention, tokens)

Another possible task for BERT training is Next Sentence Prediction.

How BERT's heads looks at tokens in that case?

In [71]:
inputs = tokenizer.encode("I'm waiting for important call", "I can't go out right now", return_tensors="pt")
outputs = model(inputs)
attention = outputs.attentions
tokens = tokenizer.convert_ids_to_tokens(inputs[0])

model_view(attention, tokens)

In [72]:
head_view(attention, tokens)

It looks interesting, doesn't it?

If you want to find out more about attention patterns, you can refer to special "field" of science - [BERTology](https://huggingface.co/docs/transformers/main/en/bertology).



---

### Tuning pretrained transfomers (for your own task and 2 points)

Important benefit of using big models is their ability to adapt to various tasks without spending a lot of time and resources for full training.

You could've heard about backbone models in another ML tasks, when they're tuned using specific data.

It's possible to tune model's weights directly, but you also can freeze model, use its outputs as knowledge and then extract neccessary information using much smaller neural networks.

#### Introduction

Here's an example of tuned BERT base model for Named Entity Recognition (NER) task:

In [ ]:
tokenizer = transformers.AutoTokenizer.from_pretrained("dslim/bert-base-NER")
model = transformers.AutoModelForTokenClassification.from_pretrained("dslim/bert-base-NER")

In [74]:
model

BertForTokenClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=9, bias=True)
)

As you can see, there's an additional classifier besides original BERT content. That layer is used to predict NER-classes for each BERT's token output.

BERT is suitable for tuning for different tasks since it outputs token embeddings and the whole data embedding in `[CLS]`-token as well.

#### Data preparation

In [8]:
import datasets

In [9]:
dataset = datasets.load_dataset("lhoestq/conll2003")

In [77]:
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3453
    })
})

In [78]:
dataset["train"][0]

{'id': '0',
 'tokens': ['EU',
  'rejects',
  'German',
  'call',
  'to',
  'boycott',
  'British',
  'lamb',
  '.'],
 'pos_tags': [22, 42, 16, 21, 35, 37, 16, 21, 7],
 'chunk_tags': [11, 21, 11, 12, 21, 22, 11, 12, 0],
 'ner_tags': [3, 0, 7, 0, 0, 0, 7, 0, 0]}

Since BERT tokenization is different from the dataset's one, we need to fix that divergence.

**Task 3 (0.5 points)**
- Align dataset token labels to WordPiece tokens
- Handle special tokens as well

In [10]:
from transformers import AutoTokenizer, DataCollatorForTokenClassification
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

def tokenize_and_align_labels(samples):
    tokenized_inputs = tokenizer(samples["tokens"], truncation=True, is_split_into_words=True)
    labels = []
    for i, original_labels in enumerate(samples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)

        aligned_labels = []

        for word_id in word_ids:
            if word_id is None:
                aligned_labels.append(-100)
            else:
                aligned_labels.append(original_labels[word_id])

        labels.append(aligned_labels)

    tokenized_inputs["labels"] = labels

    return tokenized_inputs

In [11]:
tokenized_dataset = dataset.map(tokenize_and_align_labels, batched=True)

In [86]:
tokenized_dataset["train"][0]

{'id': '0',
 'tokens': ['EU',
  'rejects',
  'German',
  'call',
  'to',
  'boycott',
  'British',
  'lamb',
  '.'],
 'pos_tags': [22, 42, 16, 21, 35, 37, 16, 21, 7],
 'chunk_tags': [11, 21, 11, 12, 21, 22, 11, 12, 0],
 'ner_tags': [3, 0, 7, 0, 0, 0, 7, 0, 0],
 'input_ids': [101,
  7270,
  22961,
  1528,
  1840,
  1106,
  21423,
  1418,
  2495,
  12913,
  119,
  102],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 'labels': [-100, 3, 0, 7, 0, 0, 0, 7, 0, 0, 0, -100]}

In [12]:
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

Now dataset is ready to be used by BERT.

#### Model preparation

For our task we can use `AutoModelForTokenClassification`, which already provides required architecture with token classifier (e.g. classifier itself, class outputs).

You can handle these things by yourself: create PyTorch model class, init BERT model and Linear layer for classification, then override forward method and so on...

`AutoModelForTokenClassification` is chosen for the sake of simplicity, but it's still required for MLE to be capable of doing it with bare hands.

In [23]:
from transformers import AutoModelForTokenClassification

id2label = {0: "O", 1: "B-PER", 2: "I-PER", 3: "B-ORG", 4: "I-ORG", 5: "B-LOC", 6: "I-LOC", 7: "B-MISC", 8: "I-MISC"}
label2id = {label: id for id, label in id2label.items()}

model = AutoModelForTokenClassification.from_pretrained(
    "bert-base-cased",
    num_labels=9,
    id2label=id2label,
    label2id=label2id,
)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 591.84it/s]
[transformers] BertForTokenClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

#### Evaluation

Evaluation is crucial while writing papers or reporting your work results. Sometimes it can be tricky and own implementation can be buggy, so it usually preferred to calculate metrics using frameworks.

In [89]:
!pip install seqeval

Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.14.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from seqeval) (2.1.2)
Requirement already satisfied: scikit-learn>=0.21.3 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from seqeval) (1.7.1)
Requirement already satisfied: scipy>=1.8.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=0.21.3->seqeval) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=0.21.3->seqeval) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\lymuthien\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=0.21.3->seqeval) (3.6.0)
Building wheels for collected packages: seqeval
  Building wheel for seqeval (pyproject.toml): started
  Building wheel for seqeval (pyproject.toml): finished with status 'done'
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16282 sha256=d577f0dde0299cd5108f897a8b00582dd01de9baf1f9987faa4d67cd092f1dcb
  Stored in directory: c:\users\lymuthien\appdata\local\pip\cache\wheels\14\cf\a7\8f28ef376d707ff10e3922899482a2f23ef3002f8a952f47ac
Successfully built seqeval
Installing collected packages: seqeval
Successfully installed seqeval-1.2.2

Let's prepare `compute_metrics` function for the following training loop:

In [14]:
import numpy as np
from seqeval.metrics import f1_score, precision_score, recall_score
from seqeval.scheme import IOB2

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    y_true = []
    y_pred = []
    for i in range(len(predictions)):
        y_true_sample = []
        y_pred_sample = []
        for j in range(len(predictions[i])):
            if labels[i][j] == -100:
                continue

            y_true_sample.append(id2label[int(labels[i][j])])
            y_pred_sample.append(id2label[int(predictions[i][j])])

        y_true.append(y_true_sample)
        y_pred.append(y_pred_sample)

    return {
        "precision": precision_score(y_true, y_pred, mode="strict", scheme=IOB2),
        "recall": recall_score(y_true, y_pred, mode="strict", scheme=IOB2),
        "f1": f1_score(y_true, y_pred, mode="strict", scheme=IOB2),
    }

#### Training

**Task 4 (0.5 points)**
- Choose proper hyperparameters for tuning the model
- Setup HF Trainer
- Check correctness using training results

In [24]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./bert-ner",
    eval_strategy="steps",
    eval_steps=50,
    logging_steps=50,
    report_to="none",

    learning_rate=2e-5,
    num_train_epochs=2,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
)

In [25]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

Let's check metrics before training:

In [26]:
results = trainer.evaluate(tokenized_dataset["test"])
print(results)

{'eval_loss': 2.168313980102539, 'eval_precision': 0.029704976495380127, 'eval_recall': 0.1360051952871324, 'eval_f1': 0.04876020688164175}

In [ ]:
trainer.train()

In [18]:
results = trainer.evaluate(tokenized_dataset["test"])
print(results)

{'eval_loss': 0.17135114967823029, 'eval_precision': 0.8950041555083572, 'eval_recall': 0.8991557658409871, 'eval_f1': 0.8970751573491299}

Compare test metrics before and after training. Did we succeed?

**Task 5 (1 point)**
- Compare our model's result with `dslim/bert-base-NER`
- Try to improve our model's quality. Choose any option:
  - Play with training hyperparameters (batch_size, lr, epochs, etc.)
  - Apply some training techniques (warm-up, lr-scheduling, etc.)
  - Perform error analysis and find model's weak spots (this option doesn't require fixing them)
  - Your very own idea
- Write a small report (up to 5 steps, results and conclusions) on the work done in "Tuning pretrained transformers" part